# Default values for nodechart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# This one is just a demo file, the file to install the helm chart will be created through
# ANSIBLE with the values.tpl file that is in the same folder that this file.

metadata:
  #Provide the namespace for organization's peer
  #Eg. namespace: university-ns
  namespace:

  #Provide the name for student agent
  #Eg. name: student-alice
  name:

organization:
  #Provide the name for organization
  #Eg. name: university
  name:

image:
  agent:
    #Provide the image name for the alice container
    #Eg. name: student-alice
    name:

    #Provide the image repository for the alice container
    #Eg. repository: aries-agents:1.11.0
    repository:

  #Provide the image pull secret of image
  #Eg. pullSecret: regcred
  pullSecret:

service:
    ports:
      #Provide the service node port for service connections
      #Eg. endpoint: 8030
      service:

      #Provide the service node port for swagger UI
      #Eg. endpoint: 8031
      endpoint:

    #Provide the address of this agent
    #Eg. address: 192.168.99.204
    address:

    #Provide the url for Indy WebServer
    #Eg. ledger: http://192.168.99.204:8000
    ledger:

    #Provide the url for genesis
    #Eg. genesis: http://192.168.99.204:8000/genesis
    genesis:
