apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Values.metadata.name }}"
  namespace: "{{ $.Values.metadata.namespace }}"
spec:
  type: NodePort
  ports:
  - name: indy-faber-service
    port: {{ $.Values.service.ports.service }}
    targetPort: {{ $.Values.service.ports.service }}
    nodePort: {{ $.Values.service.ports.service }}
  - name: indy-faber-endpoint
    port: {{ $.Values.service.ports.endpoint }}
    targetPort: {{ $.Values.service.ports.endpoint }}
    nodePort: {{ $.Values.service.ports.endpoint }}
  selector:
    app: "{{ $.Values.metadata.name }}"
