# This task fetch node address of each node of all organizations
- name: Fetch the node address
  include_tasks: validator_node_data.yaml
  vars:
    vault: "{{ org.vault }}"
  loop: "{{ network['organizations'] }}"
  loop_control:
    loop_var: org

# This task creates the genesis file from the template
- name: Create genesis.yaml
  template:
    src: "genesis.tpl"
    dest: "{{ build_path }}/genesis.yaml"

# This task reads the genesis file and put it in the variable
- name: Read the genesis.yaml file
  set_fact:
    genesis_yaml="{{ lookup('file', '{{ build_path }}/genesis.yaml') | from_yaml }}"

# This task converts the above read variable into json format and writes it in the gensis.json file
- name: Create genesis.json file
  copy:
    content: "{{ genesis_yaml | to_nice_json }}"
    dest: "{{ network.config.genesis }}"
  when: not add_new_org
