# Default values for nodechart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# This one is just a demo file, the file to install the helm chart will be created through
# ANSIBLE with the values.tpl file that is in the same folder that this file.

metadata:
  #Provide the namespace for organization's peer
  #Eg. namespace: university-ns
  namespace:

  #Provide the name for university agent release
  #Eg. name: university-faber
  name:

organization:
  #Provide the name for organization
  #Eg. name: university
  name:

image:
  init:
    #Provide the image name for the university-faber-init container
    #Eg. name: university-faber-init
    name:

    #Provide the image repository for the university-faber-init container
    #Eg. repository: alpine:3.9.4
    repository:

  agent:
    #Provide the image name for the faber container
    #Eg. name: university-faber
    name:

    #Provide the image repository for the faber container
    #Eg. repository: aries-agents:1.11.0
    repository:

  #Provide the image pull secret of image
  #Eg. pullSecret: regcred
  pullSecret:

service:
    ports:
      #Provide the service node port for service connections
      #Eg. endpoint: 8020
      service:

      #Provide the service node port for swagger UI
      #Eg. endpoint: 8021
      endpoint:

    #Provide the address of this agent
    #Eg. address: 192.168.99.204
    address:

    #Provide the url for Indy WebServer
    #Eg. ledger: http://192.168.99.204:8000
    ledger:

    #Provide the url for genesis
    #Eg. genesis: http://192.168.99.204:8000/genesis
    genesis:


vault:
  #Provide the vault server address
  #Eg. address: http://54.226.163.39:8200
  address:

  #Provide the service account name for vault
  #Eg. serviceAccountName: university-university-endorser-vault-auth
  serviceAccountName:

  #Provide the auth path
  #Eg. authPath: kubernetes-university-university-endorser-auth
  authPath:

  #Provide the name of service
  #Eg. endorserName: university-endorser
  endorserName:

  #Provide the role
  #Eg. role: ro
  role:

storage:
  #Provide the storage size for storage for keys
  #Eg. size: 128Mi
  size:

  #Provide the storageClassName for storage for keys
  #Eg. className: university-minikube-storageclass
  className:
