---
dependencies:
  - role: "aws-auth"
    vars:
      aws_authenticator:
        version: "1.10.3"
        release_date:  "2018-07-26"
        os: "{{ install_os }}"
        arch: "{{ install_arch }}"
        bin_directory: "{{ bin_install_dir }}"
        checksum: ""
      kubeconfig_path: "{{ item.k8s.config_file }}"
      kubecontext: "{{ item.k8s.context }}"
    when: item.cloud_provider == 'aws'
  - role: "helm"
    vars:
      helm:
        version: "v2.14.1"
        os: "{{ install_os }}"
        arch: "{{ install_arch }}"
        bin_directory: "{{ bin_install_dir }}"
        checksum: ""
  - role: "kubectl"
    vars:
      kubectl:
        version: "1.14.2"
        os: "{{ install_os }}"
        arch: "{{ install_arch }}"
        bin_directory: "{{ bin_install_dir }}"
        checksum: "sha512:a4394293cecdc177db7d3ef29f9d9efb7f922d193b00d83fa17c847e2aa1cd1c38eff1f4233843fededf15d99f7c434bf701d84b93a3cb834a4699cbddf02385"
  - role: setup/tiller
      