apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Values.metadata.name }}"
  namespace: "{{ $.Values.metadata.namespace }}"
spec:
  type: NodePort
  ports:
  - name: indy-webserver
    port: {{ $.Values.service.port }}
    targetPort: 8000
    nodePort: {{ $.Values.service.port }}
  selector:
    app: "{{ $.Values.metadata.name }}"
