apiVersion: v1
appVersion: 1
description: A Helm chart to deploy Indy WebServer for ability running of Identity demo where is needed endpoints which Indy WebServer is provided.
name: webserver
version: 0.1.0
