#Provide the nodeName for node
#Eg. nodeName: manufacturer
nodeName:

# Provide the name of the organization/peername for which certifiactes are being created
# Eg. peerName: manufacturer
peerName: 

#Provide the replica set for node deployed
#Eg. replicas: 1
replicas:

metadata:
  #Provide the namespace
  #Eg. namespace: manufacturer-ent
  namespace:


# Provide image names
image:
  # Provide the alpine utils image.
  # NOTE: The alpine image used is the base alpine image with CURL installed.
  # Eg. initContainerName: hyperledgerlabs/alpine-utils:1.0
  initContainerName:
  # Provide the docker-registry secret created and stored in kubernetes cluster as a secret.
  # Eg. imagePullSecret: regcred
  imagePullSecret:
  pullPolicy: Always

  # This section contains the name of the image used in the deployment for pki tool.
  dockerImagePki:
    # Ex. name: corda/enterprise-pkitool
    name:
    # Ex. tag: 1.2-zulu-openjdk8u242
    tag:

#base directory ex. /opt/corda
volume:
  baseDir:

# This section contains the vault related information.
# NOTE: Make sure that the vault is already unsealed, intialized and configured to
# use the Kubernetes service account token based authentication.
vault:
  # Provide the vault address
  # Eg. address: http://vault.example.com:8200
  address:
  # Provide the vault role used.
  # Eg. role: vault-role
  role:
  # Provide the authpath configured to be used.
  # Eg. authpath: entcordacenm
  authpath:
  # Provide the service account name autheticated to vault.
  # NOTE: Make sure that the service account is already created and autheticated to use the vault.
  # Eg. serviceaccountname: vault-auth
  serviceaccountname:
  # Provide the vault path where the  certificates are stored
  # Eg. certsecretprefix: secret/manufacturer
  certsecretprefix: 
    
healthcheck:
  #Provide the interval in seconds you want to iterate after for checking certificates
  #Eg. readinesscheckinterval: 10
  readinesscheckinterval:
  # Provide this to iterate till this to check for the certificates
  # readinessthreshold: 20
  readinessthreshold:

# Provide the JVM for jar
# cordaJarMx: 1
cordaJarMx:

# Ex healthCheckNodePort: 0
healthCheckNodePort:

# where is CENM service jar file stored
# Ex. jarPath: bin
jarPath:

# where is CENM service configuration file stored
# Ex. configPath: etc
configPath:

# certificates subjects specification for generating certificates for network entity
pki:
  certificates:
    bridge:
      # subject: "CN=Test Bridge Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
      subject:
    # Float certificate specifications
    float:
      # subject: "CN=Test Float Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
      subject:
    # Firewall CA certificate specifications
    firewallca:
      #subject: "CN=Test Firewall CA Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"    
      subject:
